/**
 * Serenest Academy programs. Each renders a dedicated page at
 * /academy/programs/:slug via AcademyProgramPage, and appears in full on
 * the Academy landing page and /academy/programs catalogue.
 */

export const ACADEMY_PROGRAMS = [
  {
    slug: 'clinical-excellence',
    category: 'Clinical Practice',
    iconName: 'award', accent: 'teal', popular: true, featured: true,
    title: 'Clinical Excellence',
    subtitle: 'Flagship Course for Practicing Mental Health Professionals',
    tagline: 'The flagship course for psychiatrists, psychologists, therapists & counsellors.',
    body: 'Serenest Academy’s best course for working clinicians — assessment, evidence-based care, telepsychiatry, documentation, and measurement-based practice.',
    overview:
      'Our flagship program for practicing mental health professionals. Build clinical excellence across assessment, formulation, evidence-based interventions, telepsychiatry, documentation, ethics, and measurement-based care — designed for real Indian practice, free for approved Serenest professionals.',
    metrics: [
      { top: '12', sub: 'Weeks' },
      { top: '8', sub: 'Clinical Modules' },
      { top: 'Certificate', sub: 'Included' },
    ],
    highlights: [
      'Flagship for practicing clinicians',
      'Free for Serenest professionals',
      'Case-based + live supervision',
      'Certificate of completion',
    ],
    ctaLabel: 'Start Clinical Excellence',
    learn: [
      'Structured psychiatric & psychological assessment for common presentations',
      'Case formulation and treatment planning you can use the same week',
      'Evidence-based approaches for depression, anxiety, ADHD, OCD, and sleep',
      'Measurement-based care with PHQ-9, GAD-7, and outcome tracking',
      'Telepsychiatry excellence: consent, rapport, safety, and continuity online',
      'SOAP notes, clinical documentation, and prescription-ready workflows',
      'Risk assessment, escalation, and crisis boundaries in remote care',
      'Ethics, confidentiality, DPDP-aware practice, and professional conduct',
      'Peer case discussions and optional 1:1 clinical supervision',
    ],
    forWho: [
      'Psychiatrists and psychiatry residents',
      'Clinical psychologists and psychotherapists',
      'Counsellors and therapists in active practice',
      'Approved Serenest professionals (included free)',
    ],
    format: 'Online · 12 weeks · Self-paced modules + live case rounds · Certificate on completion',
  },
  {
    slug: 'student-training',
    category: 'Career Entry',
    iconName: 'cap', accent: 'green', featured: true, popular: true,
    title: 'Student Training',
    subtitle: 'Flagship Pathway for Psychology, Psychiatry & Mental Health Students',
    tagline: 'The full starter pathway for psychology, psychiatry, and mental health students.',
    body: 'Serenest Academy’s main student track — foundations, assessment tools, case work, ethics, and internship readiness in one structured pathway.',
    overview:
      'Our flagship student pathway. Bridge classroom theory and real clinical work across foundations, assessment, formulation, ethics, documentation, and internship prep — built for undergraduate and postgraduate students in India who want to enter practice confident, ethical, and job-ready.',
    metrics: [
      { top: '12', sub: 'Weeks' },
      { top: '10', sub: 'Modules' },
      { top: '80+', sub: 'Hours' },
      { top: 'Certificate', sub: 'Included' },
    ],
    highlights: [
      'Flagship student pathway',
      'Case-based + live discussions',
      'Internship & placement prep',
      'Certificate of completion',
    ],
    ctaLabel: 'Start Student Training',
    modules: [
      { title: 'Mental health systems in India', body: 'Roles, pathways, and how care actually reaches patients.' },
      { title: 'Clinical foundations', body: 'Core psychology & psychiatry concepts for practice, not exams alone.' },
      { title: 'History-taking & MSE', body: 'Structured interviews and mental status examination orientation.' },
      { title: 'Screening tools', body: 'PHQ-9, GAD-7, and when (and when not) to use them.' },
      { title: 'Case formulation', body: 'Turn information into a workable clinical picture.' },
      { title: 'Common presentations', body: 'Anxiety, depression, stress, sleep, and adolescent concerns.' },
      { title: 'Ethics & boundaries', body: 'Consent, confidentiality, dual relationships, and referrals.' },
      { title: 'Clinical documentation', body: 'Clear notes, case presentation, and supervisor-ready writing.' },
      { title: 'Risk & escalation', body: 'Recognising risk and knowing when to involve a psychiatrist.' },
      { title: 'Internship readiness', body: 'CV, interviews, role expectations, and reflective practice.' },
    ],
    learn: [
      'Core concepts in clinical psychology, psychiatry basics, and mental health systems in India',
      'Structured history-taking, MSE orientation, and case formulation frameworks',
      'Using PHQ-9, GAD-7, and other validated screening tools appropriately',
      'Common presentations: anxiety, depression, stress, sleep, and adolescent concerns',
      'Ethics, confidentiality, consent, and professional boundaries',
      'Writing clear clinical notes and presenting cases to supervisors',
      'Internship and placement readiness: CV, interview, and role expectations',
      'When and how to escalate risk or refer to a psychiatrist',
      'Peer case discussions with feedback from practising clinicians',
      'Reflective practice and building a sustainable learning habit',
    ],
    forWho: [
      'Undergraduate psychology students (BA / BSc)',
      'Postgraduate psychology & counselling students (MA / MSc / MPhil track)',
      'Psychiatry and allied health trainees',
      'Fresh graduates preparing for internship or first clinical role',
    ],
    format: 'Online · 12 weeks · 10 modules · Self-paced + live case discussions · Certificate on completion',
  },
  {
    slug: 'student-assessment-skills',
    category: 'Career Entry',
    iconName: 'book', accent: 'teal', featured: true,
    title: 'Assessment Skills for Students',
    subtitle: 'History-Taking, MSE & Screening Tools',
    tagline: 'Learn to take a history, run an MSE, and use screening tools correctly.',
    body: 'Hands-on assessment practice for students — interviews, mental status exam, and validated tools without over-claiming diagnosis.',
    overview:
      'A focused student course on clinical assessment: structured history-taking, mental status examination orientation, and appropriate use of screening tools such as PHQ-9 and GAD-7. Emphasis on clarity, humility, and knowing the limits of student practice.',
    metrics: [
      { top: '6', sub: 'Weeks' },
      { top: '8', sub: 'Modules' },
      { top: 'Certificate', sub: 'Included' },
    ],
    ctaLabel: 'Start assessment skills',
    modules: [
      { title: 'Rapport & interview setup', body: 'Opening a session and putting the person at ease.' },
      { title: 'History structure', body: 'Chief concern, HPI, past, family, and social history.' },
      { title: 'MSE domains', body: 'Appearance, mood, thought, cognition, insight — what to notice.' },
      { title: 'Screening tools', body: 'PHQ-9, GAD-7, and scoring without over-interpreting.' },
      { title: 'Risk questions', body: 'Asking safely about self-harm and when to escalate.' },
      { title: 'Writing what you observed', body: 'Objective notes vs speculation.' },
      { title: 'Cultural & language factors', body: 'Assessment across Indian languages and contexts.' },
      { title: 'Practice cases', body: 'Guided interviews and feedback.' },
    ],
    learn: [
      'Structure a clinical history for common presentations',
      'Orient to mental status examination domains',
      'Administer and score PHQ-9 and GAD-7 appropriately',
      'Ask risk questions safely and escalate when needed',
      'Write clear, objective assessment notes',
      'Respect scope: screening is not diagnosis',
    ],
    forWho: [
      'Psychology and counselling students',
      'Interns starting supervised assessment work',
      'Students preparing for clinical postings',
    ],
    format: 'Online · 6 weeks · Practice cases + certificate',
  },
  {
    slug: 'student-case-formulation',
    category: 'Career Entry',
    iconName: 'microscope', accent: 'blue', featured: true,
    title: 'Case Formulation Studio',
    subtitle: 'Turn Assessment into a Clear Clinical Picture',
    tagline: 'Practice building formulations you can explain to a supervisor.',
    body: 'Case-based studio for students — predisposing, precipitating, perpetuating, and protective factors with real-world examples.',
    overview:
      'A studio-style student program that turns raw assessment information into a clear formulation. Work through predisposing, precipitating, perpetuating, and protective factors, then practice presenting your thinking to a supervisor.',
    metrics: [
      { top: '5', sub: 'Weeks' },
      { top: 'Case', sub: 'Studio' },
      { top: 'Certificate', sub: 'Included' },
    ],
    ctaLabel: 'Join formulation studio',
    modules: [
      { title: 'What formulation is (and is not)', body: 'A working hypothesis, not a final label.' },
      { title: '4P / biopsychosocial maps', body: 'Organising information without losing the person.' },
      { title: 'Linking assessment to plan', body: 'From formulation to first steps and goals.' },
      { title: 'Presenting to a supervisor', body: 'Clear, humble, structured case presentation.' },
      { title: 'Studio cases', body: 'Anxiety, depression, adjustment, and adolescent vignettes.' },
    ],
    learn: [
      'Build a simple, supervisor-ready case formulation',
      'Use 4P and biopsychosocial frameworks without jargon overload',
      'Connect formulation to initial goals and interventions',
      'Present cases clearly in peer and supervisor settings',
      'Revise formulations as new information emerges',
    ],
    forWho: [
      'Students who have basic assessment exposure',
      'Interns preparing case conferences',
      'Early trainees wanting structured practice',
    ],
    format: 'Online · 5 weeks · Studio cases + certificate',
  },
  {
    slug: 'student-internship-prep',
    category: 'Career Entry',
    iconName: 'briefcase', accent: 'amber', featured: true,
    title: 'Internship & Placement Prep',
    subtitle: 'Ready for Clinical Postings and First Roles',
    tagline: 'Get placement-ready: CV, interviews, expectations, and first-week confidence.',
    body: 'Practical prep for internships and first clinical roles — what supervisors expect, how to show up, and how to learn fast.',
    overview:
      'A short, practical course for students approaching internship, clinical posting, or a first mental-health role. Cover CV and interview basics, workplace expectations, documentation habits, and how to use supervision well.',
    metrics: [
      { top: '4', sub: 'Weeks' },
      { top: 'Placement', sub: 'Focused' },
      { top: 'Certificate', sub: 'Included' },
    ],
    ctaLabel: 'Prep for internship',
    modules: [
      { title: 'What internships actually involve', body: 'Roles, hours, and learning contracts.' },
      { title: 'CV & applications', body: 'Clinical-relevant experience without exaggeration.' },
      { title: 'Interviews & first impressions', body: 'Common questions and how to answer honestly.' },
      { title: 'Week-one habits', body: 'Notes, punctuality, asking for help, and boundaries.' },
      { title: 'Using supervision', body: 'What to bring, how to receive feedback.' },
      { title: 'Self-care under load', body: 'Staying well during intense learning periods.' },
    ],
    learn: [
      'Prepare a clear, honest clinical CV and application',
      'Interview with confidence without overselling skills',
      'Meet supervisor expectations in the first weeks',
      'Use supervision productively',
      'Protect boundaries and wellbeing during placements',
    ],
    forWho: [
      'Final-year psychology and counselling students',
      'Students applying for internships or observerships',
      'Fresh graduates entering first clinical roles',
    ],
    format: 'Online · 4 weeks · Practical worksheets + certificate',
  },
  {
    slug: 'student-ethics-practice',
    category: 'Career Entry',
    iconName: 'shield', accent: 'purple', featured: true,
    title: 'Ethics for Student Practitioners',
    subtitle: 'Consent, Confidentiality, Boundaries & Referral',
    tagline: 'Ethics you will use on day one of supervised practice.',
    body: 'Clear ethics training for students — consent, confidentiality, dual relationships, social media, and when to refer.',
    overview:
      'Ethics for students entering supervised practice in India: informed consent, confidentiality limits, dual relationships, digital boundaries, and referral. Built around realistic dilemmas, not abstract codes alone.',
    metrics: [
      { top: '4', sub: 'Weeks' },
      { top: 'Dilemma', sub: 'Cases' },
      { top: 'Certificate', sub: 'Included' },
    ],
    ctaLabel: 'Start ethics course',
    modules: [
      { title: 'Consent & capacity basics', body: 'What students must explain and document.' },
      { title: 'Confidentiality & its limits', body: 'When risk overrides privacy.' },
      { title: 'Dual relationships', body: 'Friends, family, campus, and social media.' },
      { title: 'Scope of practice', body: 'What students must not claim or do alone.' },
      { title: 'Referral & escalation', body: 'Handing over safely to a clinician.' },
      { title: 'Dilemma workshop', body: 'Work through realistic student scenarios.' },
    ],
    learn: [
      'Apply consent and confidentiality in student / intern settings',
      'Recognise dual-relationship risks on campus and online',
      'Stay within supervised scope of practice',
      'Refer and escalate appropriately',
      'Discuss ethical dilemmas with a supervisor',
    ],
    forWho: [
      'Psychology, counselling, and psychiatry students',
      'Interns in supervised placements',
      'Student volunteers in mental-health settings',
    ],
    format: 'Online · 4 weeks · Dilemma cases + certificate',
  },
  {
    slug: 'counselling-skills',
    category: 'Career Entry',
    iconName: 'people', accent: 'purple', featured: true,
    title: 'Counselling Skills',
    subtitle: 'Foundational Counselling & Therapeutic Communication',
    tagline: 'Foundational counselling and therapeutic communication.',
    body: 'Practical, case-based skill building in communication, ethics and counsellor competencies.',
    overview:
      'Practical skill-building for effective, ethical counselling — the communication, rapport, and technique foundations every mental health practitioner needs before deeper modality training.',
    metrics: [
      { top: '30+', sub: 'Skills Modules' },
      { top: 'Role-play', sub: 'Sessions' },
      { top: 'Practical', sub: 'Tools' },
    ],
    ctaLabel: 'Open counselling track',
    learn: [
      'Active listening, reflection, and therapeutic communication',
      'Building rapport and a psychologically safe space',
      'Basics of CBT-informed and supportive counselling techniques',
      'Session structure: opening, working, closing, and homework',
      'Ethical boundaries, dual relationships, and appropriate referral',
      'Working with emotion, silence, and resistance in session',
      'Cultural humility and language sensitivity in Indian practice',
      'Supervision, reflective practice, and self-care for counsellors',
    ],
    forWho: [
      'Aspiring and practicing counsellors',
      'Psychology students',
      'Allied helpers and educators',
    ],
    format: 'Online · Practical, exercise-led · Role-play practice',
  },
  {
    slug: 'certificate-programs',
    category: 'Career Entry',
    iconName: 'certificate', accent: 'amber', featured: true,
    title: 'Certificate Programs',
    subtitle: 'Short-term Professional Certifications',
    tagline: 'Short-term professional certifications.',
    body: 'Structured, clinically reviewed certificate programs for working professionals and students.',
    overview:
      'Focused, short-term certificate tracks that let working professionals and students build a specific, verifiable skill and earn a certificate of completion — without a multi-month commitment.',
    metrics: [
      { top: '10+', sub: 'Certificates' },
      { top: 'Industry', sub: 'Relevant' },
      { top: 'Flexible', sub: 'Learning' },
    ],
    ctaLabel: 'Explore certificates',
    learn: [
      'Targeted, role-relevant clinical or counselling skills',
      'Applied, case-based modules with clear learning outcomes',
      'Assessment criteria and completion requirements',
      'Documentation and workplace application tips',
      'A shareable certificate of completion from Serenest Academy',
      'Pathways into longer programs (Clinical Excellence, CPD, Fellowship)',
    ],
    forWho: [
      'Working mental health professionals',
      'Students adding a credential',
      'Career switchers exploring the field',
    ],
    format: 'Online · Short-term · Certificate on completion',
  },
  {
    slug: 'psychiatry-training',
    category: 'Clinical Practice',
    iconName: 'shield', accent: 'blue', featured: true,
    title: 'Psychiatry Training',
    subtitle: 'Clinical Psychiatry, Prescribing & Telemedicine',
    tagline: 'Clinical psychiatry, prescribing & telemedicine.',
    body: 'For residents and prescribers: telemedicine norms, prescribing conversations, and SOAP/Rx workflow.',
    overview:
      'For residents and prescribing clinicians: a practice-oriented program covering modern telepsychiatry norms, prescribing conversations, documentation, risk, and continuity of care across India.',
    metrics: [
      { top: '40+', sub: 'Clinical Modules' },
      { top: 'Prescribing', sub: 'Guides' },
      { top: 'Case-based', sub: 'Learning' },
    ],
    ctaLabel: 'Open psychiatry track',
    learn: [
      'Telemedicine practice norms, consent, and jurisdiction considerations',
      'Prescribing conversations: shared decision-making and safety netting',
      'SOAP notes, Rx documentation, and clinic workflow on Serenest',
      'Common presentations: depression, anxiety, psychosis, ADHD, sleep',
      'Risk assessment, escalation, and crisis boundaries in remote care',
      'Continuity of care between visits and hand-offs',
      'Ethics, controlled medications awareness, and professional conduct',
      'Peer case rounds and optional supervision for residents',
    ],
    forWho: [
      'Psychiatry residents',
      'Prescribing clinicians',
      'MBBS doctors moving into mental health',
    ],
    format: 'Online · Clinician-led, case-based · Certificate available',
  },
  {
    slug: 'digital-mental-health',
    category: 'Clinical Practice',
    iconName: 'monitor', accent: 'teal', featured: true,
    title: 'Digital Mental Health',
    subtitle: 'Telepsychiatry, Documentation & Remote Care',
    tagline: 'Telepsychiatry, documentation & remote care.',
    body: 'Modern, remote-care delivery with platform workflows, documentation and continuity of care.',
    overview:
      'Learn to deliver high-quality care remotely — platform workflows, secure documentation, rapport online, and the practicalities of running safe, effective telepsychiatry and teletherapy.',
    metrics: [
      { top: '25+', sub: 'Workflows' },
      { top: 'Documentation', sub: 'Templates' },
      { top: 'Telehealth', sub: 'Guides' },
    ],
    ctaLabel: 'Learn telepsychiatry',
    learn: [
      'Setting up and running a teleconsultation end-to-end',
      'Secure documentation, records, and DPDP-aware practice',
      'Building rapport over video, audio, and chat',
      'Privacy, consent, recording policies, and patient expectations',
      'Continuity and follow-up in remote care',
      'Platform workflows used on Serenest (booking, room, Rx hand-off)',
      'Safety planning and when to move care offline or escalate',
      'Quality indicators for digital mental health practice',
    ],
    forWho: [
      'Clinicians moving to online practice',
      'Psychiatrists and psychologists',
      'Digital health and care-coordination teams',
    ],
    format: 'Online · Practical, tools-led',
  },
  {
    slug: 'research-publications',
    category: 'Clinical Practice',
    iconName: 'microscope', accent: 'coral', featured: true,
    title: 'Research & Publications',
    subtitle: 'Research Methodology & Publication Support',
    tagline: 'Research methodology and publication support.',
    body: 'Support for case write-ups, literature reviews, and publication-ready clinical writing.',
    overview:
      'Support for clinicians and students who want to publish — from literature reviews and case reports to publication-ready writing, with mentorship along the way.',
    metrics: [
      { top: 'Guided', sub: 'Projects' },
      { top: 'Publication', sub: 'Mentorship' },
      { top: 'Journal', sub: 'Support' },
    ],
    ctaLabel: 'View resources',
    learn: [
      'Research methodology basics for clinical questions',
      'Conducting a focused, efficient literature review',
      'Writing case reports and clinical papers',
      'Structuring abstracts, methods, and discussion sections',
      'Choosing journals and submitting ethically',
      'Working with a publication mentor',
      'Avoiding common pitfalls (plagiarism, authorship, dual publication)',
    ],
    forWho: [
      'Postgraduate students',
      'Residents and early-career clinicians',
      'Researchers in mental health',
    ],
    format: 'Online · Mentor-supported',
  },
  {
    slug: 'cpd-programs',
    category: 'Professional Growth',
    iconName: 'target', accent: 'green', featured: true,
    title: 'CPD Programs',
    subtitle: 'Continuous Professional Development',
    tagline: 'Continuous professional development.',
    body: 'Ongoing learning for licensed professionals to stay current and meet CPD requirements.',
    overview:
      'Ongoing, structured learning that helps licensed professionals stay current with evidence, sharpen skills, and meet continuing professional development expectations — without pausing clinical work.',
    metrics: [
      { top: '100+', sub: 'CPD Activities' },
      { top: 'Expert', sub: 'Faculty' },
      { top: 'CPD', sub: 'Credits' },
    ],
    ctaLabel: 'Open CPD track',
    learn: [
      'Current, evidence-based clinical updates',
      'Refreshers on assessment, formulation, and treatment planning',
      'New modalities and best-practice summaries',
      'Measurement-based care and outcome tracking refreshers',
      'Ethics, documentation, and regulatory awareness updates',
      'Reflective practice and self-audit templates',
      'Short modules you can complete between clinic days',
    ],
    forWho: [
      'Licensed psychologists and psychiatrists',
      'Practicing counsellors and therapists',
      'Any clinician maintaining CPD',
    ],
    format: 'Online · Ongoing, flexible · CPD-oriented',
  },
  {
    slug: 'mentorship',
    category: 'Professional Growth',
    iconName: 'people', accent: 'amber', featured: true,
    title: 'Mentorship',
    subtitle: '1:1 Supervision & Career Guidance',
    tagline: '1:1 supervision and career guidance.',
    body: 'Personalized mentorship and supervision to help you grow with clarity and confidence.',
    overview:
      'Personalised, one-to-one mentorship and clinical supervision — guidance on cases, skills, and career direction from experienced clinicians who still practice.',
    metrics: [
      { top: '1:1', sub: 'Mentorship' },
      { top: 'Case', sub: 'Supervision' },
      { top: 'Career', sub: 'Guidance' },
    ],
    ctaLabel: 'Find a mentor',
    learn: [
      '1:1 clinical supervision on real cases',
      'Personalised skill development plans',
      'Career direction: specialisation, private practice, academia',
      'Reflective practice and managing clinical uncertainty',
      'Feedback on notes, formulations, and session structure',
      'Building a sustainable caseload and professional identity',
    ],
    forWho: [
      'Early-career clinicians',
      'Students seeking guidance',
      'Professionals wanting ongoing supervision',
    ],
    format: 'Online · Scheduled 1:1 sessions',
  },
  {
    slug: 'fellowship-programs',
    category: 'Professional Growth',
    iconName: 'award', accent: 'purple', featured: true,
    title: 'Fellowship Programs',
    subtitle: 'Advanced Specialty Tracks',
    tagline: 'Advanced specialty tracks.',
    body: 'In-depth fellowship programs in specialized areas of mental health practice.',
    overview:
      'In-depth, advanced specialty tracks for clinicians ready to go deeper — structured, longer-form programs building real expertise in a focused clinical area.',
    metrics: [
      { top: 'Specialty', sub: 'Tracks' },
      { top: 'Advanced', sub: 'Training' },
      { top: 'Professional', sub: 'Recognition' },
    ],
    ctaLabel: 'Explore fellowships',
    learn: [
      'Advanced, specialty-focused curriculum with depth over breadth',
      'Supervised clinical application in the chosen focus area',
      'Research or applied project component',
      'Peer cohort learning with experienced faculty',
      'A recognised fellowship credential on completion',
      'Pathways into teaching or leading within Serenest Academy',
    ],
    forWho: [
      'Experienced clinicians',
      'Specialists-in-training',
      'Professionals deepening expertise',
    ],
    format: 'Online · Longer-form, advanced · Fellowship credential',
  },
];

export const PROGRAMS_BY_SLUG = Object.fromEntries(ACADEMY_PROGRAMS.map((p) => [p.slug, p]));

/** Flagship / highlighted programs (all catalogue entries are featured on Academy home). */
export const FEATURED_PROGRAMS = ACADEMY_PROGRAMS.filter((p) => p.featured);

export const ACADEMY_CATEGORIES = [
  { label: 'Career Entry', tagline: 'Start strong. Build your foundation.' },
  { label: 'Clinical Practice', tagline: 'Learn. Practice. Deliver impact.' },
  { label: 'Professional Growth', tagline: 'Grow continuously. Lead the change.' },
];

export const ACADEMY_JOURNEY = [
  { icon: 'cap', title: 'Student', sub: 'Start your learning journey' },
  { icon: 'certificate', title: 'Certificate', sub: 'Build foundational skills' },
  { icon: 'stethoscope', title: 'Clinical Training', sub: 'Gain practical clinical expertise' },
  { icon: 'book', title: 'Research & Publication', sub: 'Contribute to evidence & knowledge' },
  { icon: 'briefcase', title: 'Professional Practice', sub: 'Deliver impact with confidence' },
  { icon: 'award', title: 'CPD & Fellowship', sub: 'Keep learning. Stay ahead.' },
];
