/**
 * Serenest Academy programs. Each renders a dedicated page at
 * /academy/programs/:slug via AcademyProgramPage, and appears in full on
 * the Academy landing page and /academy/programs catalogue.
 */

export const ACADEMY_PROGRAMS = [
  {
    slug: 'clinical-excellence',
    category: 'Clinical Practice',
    iconName: 'award', accent: 'teal', popular: true, featured: true,
    title: 'Clinical Excellence',
    subtitle: 'Flagship Course for Practicing Mental Health Professionals',
    tagline: 'The flagship course for psychiatrists, psychologists, therapists & counsellors.',
    body: 'Serenest Academy’s best course for working clinicians — assessment, evidence-based care, telepsychiatry, documentation, and measurement-based practice.',
    overview:
      'Our flagship program for practicing mental health professionals. Build clinical excellence across assessment, formulation, evidence-based interventions, telepsychiatry, documentation, ethics, and measurement-based care — designed for real Indian practice, free for approved Serenest professionals.',
    metrics: [
      { top: '12', sub: 'Weeks' },
      { top: '8', sub: 'Clinical Modules' },
      { top: 'Certificate', sub: 'Included' },
    ],
    highlights: [
      'Flagship for practicing clinicians',
      'Free for Serenest professionals',
      'Case-based + live supervision',
      'Certificate of completion',
    ],
    ctaLabel: 'Start Clinical Excellence',
    learn: [
      'Structured psychiatric & psychological assessment for common presentations',
      'Case formulation and treatment planning you can use the same week',
      'Evidence-based approaches for depression, anxiety, ADHD, OCD, and sleep',
      'Measurement-based care with PHQ-9, GAD-7, and outcome tracking',
      'Telepsychiatry excellence: consent, rapport, safety, and continuity online',
      'SOAP notes, clinical documentation, and prescription-ready workflows',
      'Risk assessment, escalation, and crisis boundaries in remote care',
      'Ethics, confidentiality, DPDP-aware practice, and professional conduct',
      'Peer case discussions and optional 1:1 clinical supervision',
    ],
    forWho: [
      'Psychiatrists and psychiatry residents',
      'Clinical psychologists and psychotherapists',
      'Counsellors and therapists in active practice',
      'Approved Serenest professionals (included free)',
    ],
    format: 'Online · 12 weeks · Self-paced modules + live case rounds · Certificate on completion',
  },
  {
    slug: 'student-training',
    category: 'Career Entry',
    iconName: 'cap', accent: 'green', featured: true,
    title: 'Student Training',
    subtitle: 'For Psychology, Psychiatry & Mental Health Students',
    tagline: 'For Psychology, Psychiatry & Mental Health students.',
    body: 'Foundational and applied training for students entering the mental health field.',
    overview:
      'A foundational, case-based program that bridges classroom theory and real clinical work. Built for undergraduate and postgraduate students who want to enter practice confident, ethical, and job-ready — with assessment tools, formulation, and internship preparation.',
    metrics: [
      { top: '50+', sub: 'Hours Training' },
      { top: 'Case', sub: 'Discussions' },
      { top: 'Certificate', sub: 'Included' },
    ],
    ctaLabel: 'Explore student track',
    learn: [
      'Core concepts in clinical psychology, psychiatry basics, and mental health systems in India',
      'Structured history-taking, MSE orientation, and case formulation frameworks',
      'Using PHQ-9, GAD-7, and other validated screening tools appropriately',
      'Ethics, confidentiality, consent, and professional boundaries',
      'Writing clear clinical notes and presenting cases to supervisors',
      'Internship and placement readiness: CV, interview, and role expectations',
      'When and how to escalate risk or refer to a psychiatrist',
      'Reflective practice and building a sustainable learning habit',
    ],
    forWho: [
      'Undergraduate & postgraduate psychology students',
      'Psychiatry and allied health trainees',
      'Fresh graduates entering practice',
    ],
    format: 'Online · Self-paced with live case discussions · Certificate on completion',
  },
  {
    slug: 'counselling-skills',
    category: 'Career Entry',
    iconName: 'people', accent: 'purple', featured: true,
    title: 'Counselling Skills',
    subtitle: 'Foundational Counselling & Therapeutic Communication',
    tagline: 'Foundational counselling and therapeutic communication.',
    body: 'Practical, case-based skill building in communication, ethics and counsellor competencies.',
    overview:
      'Practical skill-building for effective, ethical counselling — the communication, rapport, and technique foundations every mental health practitioner needs before deeper modality training.',
    metrics: [
      { top: '30+', sub: 'Skills Modules' },
      { top: 'Role-play', sub: 'Sessions' },
      { top: 'Practical', sub: 'Tools' },
    ],
    ctaLabel: 'Open counselling track',
    learn: [
      'Active listening, reflection, and therapeutic communication',
      'Building rapport and a psychologically safe space',
      'Basics of CBT-informed and supportive counselling techniques',
      'Session structure: opening, working, closing, and homework',
      'Ethical boundaries, dual relationships, and appropriate referral',
      'Working with emotion, silence, and resistance in session',
      'Cultural humility and language sensitivity in Indian practice',
      'Supervision, reflective practice, and self-care for counsellors',
    ],
    forWho: [
      'Aspiring and practicing counsellors',
      'Psychology students',
      'Allied helpers and educators',
    ],
    format: 'Online · Practical, exercise-led · Role-play practice',
  },
  {
    slug: 'certificate-programs',
    category: 'Career Entry',
    iconName: 'certificate', accent: 'amber', featured: true,
    title: 'Certificate Programs',
    subtitle: 'Short-term Professional Certifications',
    tagline: 'Short-term professional certifications.',
    body: 'Structured, clinically reviewed certificate programs for working professionals and students.',
    overview:
      'Focused, short-term certificate tracks that let working professionals and students build a specific, verifiable skill and earn a certificate of completion — without a multi-month commitment.',
    metrics: [
      { top: '10+', sub: 'Certificates' },
      { top: 'Industry', sub: 'Relevant' },
      { top: 'Flexible', sub: 'Learning' },
    ],
    ctaLabel: 'Explore certificates',
    learn: [
      'Targeted, role-relevant clinical or counselling skills',
      'Applied, case-based modules with clear learning outcomes',
      'Assessment criteria and completion requirements',
      'Documentation and workplace application tips',
      'A shareable certificate of completion from Serenest Academy',
      'Pathways into longer programs (Clinical Excellence, CPD, Fellowship)',
    ],
    forWho: [
      'Working mental health professionals',
      'Students adding a credential',
      'Career switchers exploring the field',
    ],
    format: 'Online · Short-term · Certificate on completion',
  },
  {
    slug: 'psychiatry-training',
    category: 'Clinical Practice',
    iconName: 'shield', accent: 'blue', featured: true,
    title: 'Psychiatry Training',
    subtitle: 'Clinical Psychiatry, Prescribing & Telemedicine',
    tagline: 'Clinical psychiatry, prescribing & telemedicine.',
    body: 'For residents and prescribers: telemedicine norms, prescribing conversations, and SOAP/Rx workflow.',
    overview:
      'For residents and prescribing clinicians: a practice-oriented program covering modern telepsychiatry norms, prescribing conversations, documentation, risk, and continuity of care across India.',
    metrics: [
      { top: '40+', sub: 'Clinical Modules' },
      { top: 'Prescribing', sub: 'Guides' },
      { top: 'Case-based', sub: 'Learning' },
    ],
    ctaLabel: 'Open psychiatry track',
    learn: [
      'Telemedicine practice norms, consent, and jurisdiction considerations',
      'Prescribing conversations: shared decision-making and safety netting',
      'SOAP notes, Rx documentation, and clinic workflow on Serenest',
      'Common presentations: depression, anxiety, psychosis, ADHD, sleep',
      'Risk assessment, escalation, and crisis boundaries in remote care',
      'Continuity of care between visits and hand-offs',
      'Ethics, controlled medications awareness, and professional conduct',
      'Peer case rounds and optional supervision for residents',
    ],
    forWho: [
      'Psychiatry residents',
      'Prescribing clinicians',
      'MBBS doctors moving into mental health',
    ],
    format: 'Online · Clinician-led, case-based · Certificate available',
  },
  {
    slug: 'digital-mental-health',
    category: 'Clinical Practice',
    iconName: 'monitor', accent: 'teal', featured: true,
    title: 'Digital Mental Health',
    subtitle: 'Telepsychiatry, Documentation & Remote Care',
    tagline: 'Telepsychiatry, documentation & remote care.',
    body: 'Modern, remote-care delivery with platform workflows, documentation and continuity of care.',
    overview:
      'Learn to deliver high-quality care remotely — platform workflows, secure documentation, rapport online, and the practicalities of running safe, effective telepsychiatry and teletherapy.',
    metrics: [
      { top: '25+', sub: 'Workflows' },
      { top: 'Documentation', sub: 'Templates' },
      { top: 'Telehealth', sub: 'Guides' },
    ],
    ctaLabel: 'Learn telepsychiatry',
    learn: [
      'Setting up and running a teleconsultation end-to-end',
      'Secure documentation, records, and DPDP-aware practice',
      'Building rapport over video, audio, and chat',
      'Privacy, consent, recording policies, and patient expectations',
      'Continuity and follow-up in remote care',
      'Platform workflows used on Serenest (booking, room, Rx hand-off)',
      'Safety planning and when to move care offline or escalate',
      'Quality indicators for digital mental health practice',
    ],
    forWho: [
      'Clinicians moving to online practice',
      'Psychiatrists and psychologists',
      'Digital health and care-coordination teams',
    ],
    format: 'Online · Practical, tools-led',
  },
  {
    slug: 'research-publications',
    category: 'Clinical Practice',
    iconName: 'microscope', accent: 'coral', featured: true,
    title: 'Research & Publications',
    subtitle: 'Research Methodology & Publication Support',
    tagline: 'Research methodology and publication support.',
    body: 'Support for case write-ups, literature reviews, and publication-ready clinical writing.',
    overview:
      'Support for clinicians and students who want to publish — from literature reviews and case reports to publication-ready writing, with mentorship along the way.',
    metrics: [
      { top: 'Guided', sub: 'Projects' },
      { top: 'Publication', sub: 'Mentorship' },
      { top: 'Journal', sub: 'Support' },
    ],
    ctaLabel: 'View resources',
    learn: [
      'Research methodology basics for clinical questions',
      'Conducting a focused, efficient literature review',
      'Writing case reports and clinical papers',
      'Structuring abstracts, methods, and discussion sections',
      'Choosing journals and submitting ethically',
      'Working with a publication mentor',
      'Avoiding common pitfalls (plagiarism, authorship, dual publication)',
    ],
    forWho: [
      'Postgraduate students',
      'Residents and early-career clinicians',
      'Researchers in mental health',
    ],
    format: 'Online · Mentor-supported',
  },
  {
    slug: 'cpd-programs',
    category: 'Professional Growth',
    iconName: 'target', accent: 'green', featured: true,
    title: 'CPD Programs',
    subtitle: 'Continuous Professional Development',
    tagline: 'Continuous professional development.',
    body: 'Ongoing learning for licensed professionals to stay current and meet CPD requirements.',
    overview:
      'Ongoing, structured learning that helps licensed professionals stay current with evidence, sharpen skills, and meet continuing professional development expectations — without pausing clinical work.',
    metrics: [
      { top: '100+', sub: 'CPD Activities' },
      { top: 'Expert', sub: 'Faculty' },
      { top: 'CPD', sub: 'Credits' },
    ],
    ctaLabel: 'Open CPD track',
    learn: [
      'Current, evidence-based clinical updates',
      'Refreshers on assessment, formulation, and treatment planning',
      'New modalities and best-practice summaries',
      'Measurement-based care and outcome tracking refreshers',
      'Ethics, documentation, and regulatory awareness updates',
      'Reflective practice and self-audit templates',
      'Short modules you can complete between clinic days',
    ],
    forWho: [
      'Licensed psychologists and psychiatrists',
      'Practicing counsellors and therapists',
      'Any clinician maintaining CPD',
    ],
    format: 'Online · Ongoing, flexible · CPD-oriented',
  },
  {
    slug: 'mentorship',
    category: 'Professional Growth',
    iconName: 'people', accent: 'amber', featured: true,
    title: 'Mentorship',
    subtitle: '1:1 Supervision & Career Guidance',
    tagline: '1:1 supervision and career guidance.',
    body: 'Personalized mentorship and supervision to help you grow with clarity and confidence.',
    overview:
      'Personalised, one-to-one mentorship and clinical supervision — guidance on cases, skills, and career direction from experienced clinicians who still practice.',
    metrics: [
      { top: '1:1', sub: 'Mentorship' },
      { top: 'Case', sub: 'Supervision' },
      { top: 'Career', sub: 'Guidance' },
    ],
    ctaLabel: 'Find a mentor',
    learn: [
      '1:1 clinical supervision on real cases',
      'Personalised skill development plans',
      'Career direction: specialisation, private practice, academia',
      'Reflective practice and managing clinical uncertainty',
      'Feedback on notes, formulations, and session structure',
      'Building a sustainable caseload and professional identity',
    ],
    forWho: [
      'Early-career clinicians',
      'Students seeking guidance',
      'Professionals wanting ongoing supervision',
    ],
    format: 'Online · Scheduled 1:1 sessions',
  },
  {
    slug: 'fellowship-programs',
    category: 'Professional Growth',
    iconName: 'award', accent: 'purple', featured: true,
    title: 'Fellowship Programs',
    subtitle: 'Advanced Specialty Tracks',
    tagline: 'Advanced specialty tracks.',
    body: 'In-depth fellowship programs in specialized areas of mental health practice.',
    overview:
      'In-depth, advanced specialty tracks for clinicians ready to go deeper — structured, longer-form programs building real expertise in a focused clinical area.',
    metrics: [
      { top: 'Specialty', sub: 'Tracks' },
      { top: 'Advanced', sub: 'Training' },
      { top: 'Professional', sub: 'Recognition' },
    ],
    ctaLabel: 'Explore fellowships',
    learn: [
      'Advanced, specialty-focused curriculum with depth over breadth',
      'Supervised clinical application in the chosen focus area',
      'Research or applied project component',
      'Peer cohort learning with experienced faculty',
      'A recognised fellowship credential on completion',
      'Pathways into teaching or leading within Serenest Academy',
    ],
    forWho: [
      'Experienced clinicians',
      'Specialists-in-training',
      'Professionals deepening expertise',
    ],
    format: 'Online · Longer-form, advanced · Fellowship credential',
  },
];

export const PROGRAMS_BY_SLUG = Object.fromEntries(ACADEMY_PROGRAMS.map((p) => [p.slug, p]));

/** Flagship / highlighted programs (all catalogue entries are featured on Academy home). */
export const FEATURED_PROGRAMS = ACADEMY_PROGRAMS.filter((p) => p.featured);

export const ACADEMY_CATEGORIES = [
  { label: 'Career Entry', tagline: 'Start strong. Build your foundation.' },
  { label: 'Clinical Practice', tagline: 'Learn. Practice. Deliver impact.' },
  { label: 'Professional Growth', tagline: 'Grow continuously. Lead the change.' },
];

export const ACADEMY_JOURNEY = [
  { icon: 'cap', title: 'Student', sub: 'Start your learning journey' },
  { icon: 'certificate', title: 'Certificate', sub: 'Build foundational skills' },
  { icon: 'stethoscope', title: 'Clinical Training', sub: 'Gain practical clinical expertise' },
  { icon: 'book', title: 'Research & Publication', sub: 'Contribute to evidence & knowledge' },
  { icon: 'briefcase', title: 'Professional Practice', sub: 'Deliver impact with confidence' },
  { icon: 'award', title: 'CPD & Fellowship', sub: 'Keep learning. Stay ahead.' },
];
