-- ============================================================
-- 2026-08-13 — SUPERSEDED. Do not run.
--
-- Replaced by 2026_08_13b_fix_status_history_trigger_timing.sql.
--
-- This migration was never applied to production, and it was wrong:
--   * It wrote to application_status_history(application_id, old_status,
--     new_status, note) — there is no "note" column on that table. The real
--     columns are changed_by, changed_by_email, changed_at, source.
--   * It replaced the working log_application_status_change() audit writer
--     (which populates changed_by / changed_by_email / source) with a version
--     that dropped those columns.
--   * It rebuilt the foreign key as DEFERRABLE to paper over the failure,
--     when the actual defect was trigger timing: the history writer ran as
--     BEFORE INSERT, referencing NEW.id before the parent row existed.
--
-- Running it would have failed on the missing "note" column, and had it
-- succeeded it would have silently degraded the approval audit trail.
--
-- Intentionally left as a no-op so historical migration runs stay ordered.
-- ============================================================

select 1;
